AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Starting template for an AWS Serverless Application.
Resources:
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: UserId
        AttributeType: S
      - AttributeName: DataId
        AttributeType: S
      KeySchema:
      - AttributeName: UserId
        KeyType: HASH
      - AttributeName: DataId
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: QueryFunction::QueryFunction.Function::FunctionHandler
      Runtime: dotnetcore2.1
      CodeUri: s3://dev.genesis.eventdriven/0b429772a64e2c515271767ff441faaa
      MemorySize: 256
      Timeout: 30
      Role: null
      Environment:
        Variables:
          TableName:
            Ref: DataTable
      Policies:
      - AWSLambdaFullAccess
      Events:
        DataGet:
          Type: Api
          Properties:
            Method: GET
            Path: /data/{userId}/{dataId}
        PatientDataGet:
          Type: Api
          Properties:
            Method: GET
            Path: /data/{userId}
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
